# need to declare the language as well as the matrix below
language: node_js

os:
  - windows

node_js:
  - 13
  - 12
  - 10

env: "DEPLOY_VERSION=testing"

install:
  - "node . install"

script:
  - "node . test -- -t600 -Rclassic -c"
